sudo: required

services:
  - docker

before_install:
  - img=mesosphere/aws-cli:1.14.5@sha256:7d42da4ea2da6fe7d8769aef2bd9620697214ee2757ac15abaa3f4cda601bc07; docker pull $img && docker tag $img mesosphere/aws-cli
  - img=jojomi/hugo:0.62.2@sha256:68a292a0373eb3c0bb81ffaf5ff78076e60709a2937826bd02ad6fbee781e413; docker pull $img && docker tag $img jojomi/hugo

script:
  - docker run -v $(pwd):/project -w /project jojomi/hugo hugo -v

after_success:
  - docker run -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION -e BUCKET_NAME     -v $(pwd):/project                      mesosphere/aws-cli s3 sync --acl "public-read" --sse "AES256" public/ s3://$BUCKET_NAME --exclude 'post'
  - docker run -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION -e DISTRIBUTION_ID -v $(pwd):/project --entrypoint=/bin/sh mesosphere/aws-cli -c 'aws configure set preview.cloudfront true && aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths /index.html / /page/* /post/* /amp/*'
